// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb8JTWaqC9Bv3EfGlk-SgrAOXRO4faXXc',
    appId: '1:824294761230:web:785c883c321cd2afca6d5f',
    messagingSenderId: '824294761230',
    projectId: 'food-solutions-27c92',
    authDomain: 'food-solutions-27c92.firebaseapp.com',
    storageBucket: 'food-solutions-27c92.firebasestorage.app',
    measurementId: 'G-C14D6KP5E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjgnC7oIU8TaDaqIxczf2e3PMr9PlZA7Y',
    appId: '1:824294761230:android:3f8dc7a1f6733a2bca6d5f',
    messagingSenderId: '824294761230',
    projectId: 'food-solutions-27c92',
    storageBucket: 'food-solutions-27c92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZcK2qKDfsYFi7lfSHFsyzn7x8xqpfrU',
    appId: '1:824294761230:ios:ab4ac9daf92f10eaca6d5f',
    messagingSenderId: '824294761230',
    projectId: 'food-solutions-27c92',
    storageBucket: 'food-solutions-27c92.firebasestorage.app',
    iosBundleId: 'com.ak.foodsolutions.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMZcK2qKDfsYFi7lfSHFsyzn7x8xqpfrU',
    appId: '1:824294761230:ios:2f0177fce4e84ebbca6d5f',
    messagingSenderId: '824294761230',
    projectId: 'food-solutions-27c92',
    storageBucket: 'food-solutions-27c92.firebasestorage.app',
    iosBundleId: 'com.example.foodSolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb8JTWaqC9Bv3EfGlk-SgrAOXRO4faXXc',
    appId: '1:824294761230:web:d963b30ad1351cc8ca6d5f',
    messagingSenderId: '824294761230',
    projectId: 'food-solutions-27c92',
    authDomain: 'food-solutions-27c92.firebaseapp.com',
    storageBucket: 'food-solutions-27c92.firebasestorage.app',
    measurementId: 'G-RK1CDQ5Z7K',
  );
}
